# Linear_Regression

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"C:\Users\dell\Desktop\NEC\ChengduPM20100101_20151231.csv")
df.head()

No  year  month  day  hour  season  PM_Caotangsi  PM_Shahepu  PM_US Post  \
0   1  2010      1    1     0       4           NaN         NaN         NaN   
1   2  2010      1    1     1       4           NaN         NaN         NaN   
2   3  2010      1    1     2       4           NaN         NaN         NaN   
3   4  2010      1    1     3       4           NaN         NaN         NaN   
4   5  2010      1    1     4       4           NaN         NaN         NaN   

   DEWP   HUMI    PRES  TEMP cbwd  Iws  precipitation  Iprec  
0   4.0  81.20  1022.0   7.0   cv  1.0            0.0    0.0  
1   4.0  86.99  1022.0   6.0   cv  1.0            0.0    0.0  
2   4.0  86.99  1021.0   6.0   cv  1.0            0.0    0.0  
3   3.0  86.89  1021.0   5.0   cv  1.0            0.0    0.0  
4   2.0  86.79  1021.0   4.0   cv  1.0            0.0    0.0

In [3]:
df.isnull().sum()

No                   0
year                 0
month                0
day                  0
hour                 0
season               0
PM_Caotangsi     28164
PM_Shahepu       27990
PM_US Post       23684
DEWP               529
HUMI               535
PRES               521
TEMP               527
cbwd               521
Iws                533
precipitation     2955
Iprec             2955
dtype: int64

In [4]:
df.describe()

No          year         month           day          hour  \
count  52584.000000  52584.000000  52584.000000  52584.000000  52584.000000   
mean   26292.500000   2012.499772      6.523962     15.726609     11.500000   
std    15179.837614      1.707485      3.448452      8.798896      6.922252   
min        1.000000   2010.000000      1.000000      1.000000      0.000000   
25%    13146.750000   2011.000000      4.000000      8.000000      5.750000   
50%    26292.500000   2012.000000      7.000000     16.000000     11.500000   
75%    39438.250000   2014.000000     10.000000     23.000000     17.250000   
max    52584.000000   2015.000000     12.000000     31.000000     23.000000   

             season  PM_Caotangsi    PM_Shahepu    PM_US Post          DEWP  \
count  52584.000000  24420.000000  24594.000000  28900.000000  52055.000000   
mean       2.491100     77.507002     75.555867     83.407612     12.274556   
std        1.116988     60.150955     60.337735     57.239585      7.531846   
min        1.000000      3.000000      1.000000      1.000000    -16.000000   
25%        1.000000     37.000000     35.000000     44.000000      6.000000   
50%        2.000000     60.000000     57.000000     68.000000     13.000000   
75%        3.000000     99.000000     97.000000    105.000000     19.000000   
max        4.000000    662.000000    573.000000    688.000000     28.000000   

               HUMI          PRES          TEMP           Iws  precipitation  \
count  52049.000000  52063.000000  52057.000000  52051.000000   49629.000000   
mean      73.224697   1014.621985     17.698158      4.347654       0.107161   
std       17.819088      8.111353      7.843607      6.423547       1.023369   
min       12.780000    991.000000     -3.000000      0.000000       0.000000   
25%       61.440000   1008.000000     11.000000      1.000000       0.000000   
50%       77.010000   1014.900000     18.000000      2.000000       0.000000   
75%       87.750000   1021.000000     24.000000      5.000000       0.000000   
max      100.000000   1041.000000     38.000000    120.000000      57.000000   

              Iprec  
count  49629.000000  
mean       0.591557  
std        5.117582  
min        0.000000  
25%        0.000000  
50%        0.000000  
75%        0.000000  
max      169.400000

In [5]:
df.count()

No               52584
year             52584
month            52584
day              52584
hour             52584
season           52584
PM_Caotangsi     24420
PM_Shahepu       24594
PM_US Post       28900
DEWP             52055
HUMI             52049
PRES             52063
TEMP             52057
cbwd             52063
Iws              52051
precipitation    49629
Iprec            49629
dtype: int64

In [6]:
df.columns

Index(['No', 'year', 'month', 'day', 'hour', 'season', 'PM_Caotangsi',
       'PM_Shahepu', 'PM_US Post', 'DEWP', 'HUMI', 'PRES', 'TEMP', 'cbwd',
       'Iws', 'precipitation', 'Iprec'],
      dtype='object')

In [7]:
df1=df.drop(['No','year','month','day','hour','season','HUMI','PRES','Iws','precipitation','Iprec','PM_Caotangsi','PM_Shahepu','PM_US Post','cbwd'],axis = 1)
df1.head()

DEWP  TEMP
0   4.0   7.0
1   4.0   6.0
2   4.0   6.0
3   3.0   5.0
4   2.0   4.0

In [8]:
df1.shape

(52584, 2)

In [9]:
df2=df1.dropna(axis = 0)
df2.head()

DEWP  TEMP
0   4.0   7.0
1   4.0   6.0
2   4.0   6.0
3   3.0   5.0
4   2.0   4.0

In [10]:
df2.isnull().sum()

DEWP    0
TEMP    0
dtype: int64

In [11]:
df3 = (df2-df2.min())/(df2.max()-df2.min())
df3.head()

DEWP      TEMP
0  0.454545  0.243902
1  0.454545  0.219512
2  0.454545  0.219512
3  0.431818  0.195122
4  0.409091  0.170732

In [12]:
df_n= df3.select_dtypes(include = [np.number])
df_l = df_n.loc[:,['DEWP','TEMP']]
df_l.head()

DEWP      TEMP
0  0.454545  0.243902
1  0.454545  0.219512
2  0.454545  0.219512
3  0.431818  0.195122
4  0.409091  0.170732

In [13]:
df_l.shape

(52049, 2)

In [14]:
x = np.array(df_l['DEWP']).reshape(52049,1)
y = np.array(df_l['TEMP']).reshape(52049,1)
x.shape
y.shape

(52049, 1)

In [15]:
from sklearn.model_selection import train_test_split
from sklearn import datasets, linear_model

In [16]:
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=0.20)
print(X_train.shape, Y_train.shape)
print(X_test.shape, Y_test.shape)

(41639, 1) (41639, 1)
(10410, 1) (10410, 1)


In [17]:
from sklearn.linear_model import LinearRegression

In [18]:
reg = LinearRegression()
reg.fit(X_train , Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [19]:
reg.coef_

array([[0.9251823]])

In [20]:
reg.intercept_

array([-0.08954448])

In [21]:
Y_prediction = reg.predict(X_test)
Y_prediction

array([[0.33099293],
       [0.30996606],
       [0.43612728],
       ...,
       [0.66742286],
       [0.45715415],
       [0.5622885 ]])

In [22]:
a = pd.DataFrame({"actual":list(Y_test),"prediction":list(Y_prediction)})
a.head()

actual            prediction
0   [0.7073170731707317]  [0.3309929285651687]
1   [0.1951219512195122]  [0.3099660581141575]
2  [0.34146341463414637]  [0.4361272808202248]
3   [0.6341463414634146]   [0.667422855781348]
4   [0.7317073170731707]  [0.5833153739773032]

In [23]:
from sklearn import metrics
print(metrics.mean_squared_error(Y_test,Y_prediction))

0.011452417378156577


In [24]:
print(metrics.mean_absolute_error(Y_test,Y_prediction))

0.08376906494094276


In [25]:
print(np.sqrt(metrics.mean_absolute_error(Y_test,Y_prediction)))

0.28942885989642214
