In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_digits

In [16]:
digit = load_digits()
x = digit.data
y = digit.target

In [17]:
df = pd.DataFrame(digit.data)
df.head()

0    1    2     3     4     5    6    7    8    9  ...    54   55   56  \
0  0.0  0.0  5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
1  0.0  0.0  0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
2  0.0  0.0  0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0 ...   5.0  0.0  0.0   
3  0.0  0.0  7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0 ...   9.0  0.0  0.0   
4  0.0  0.0  0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   

    57   58    59    60    61   62   63  
0  0.0  6.0  13.0  10.0   0.0  0.0  0.0  
1  0.0  0.0  11.0  16.0  10.0  0.0  0.0  
2  0.0  0.0   3.0  11.0  16.0  9.0  0.0  
3  0.0  7.0  13.0  13.0   9.0  0.0  0.0  
4  0.0  0.0   2.0  16.0   4.0  0.0  0.0  

[5 rows x 64 columns]

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=0.25,random_state = 1)
print(X_train.shape, Y_train.shape)
print(X_test.shape, Y_test.shape)

(1347, 64) (1347,)
(450, 64) (450,)


In [21]:
from sklearn.preprocessing import StandardScaler
x_std = StandardScaler()
x_std.fit_transform(X_train,Y_train)

array([[ 0.        , -0.3349674 ,  0.37655956, ..., -0.62448267,
        -0.50368434, -0.19356921],
       [ 0.        , -0.3349674 , -1.10038723, ...,  0.72870962,
         0.98145861, -0.19356921],
       [ 0.        , -0.3349674 , -1.10038723, ...,  0.39041155,
        -0.50368434, -0.19356921],
       ...,
       [ 0.        , -0.3349674 ,  0.37655956, ...,  1.0670077 ,
        -0.00863669, -0.19356921],
       [ 0.        , -0.3349674 , -1.10038723, ...,  1.57445481,
        -0.25616051, -0.19356921],
       [ 0.        , -0.3349674 ,  0.58755196, ..., -1.13192978,
        -0.50368434, -0.19356921]])

In [12]:
from sklearn.decomposition import PCA
model = PCA(n_components=2)
model.fit(x_std)

PCA(copy=True, iterated_power='auto', n_components=2, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [22]:
from sklearn.linear_model import LogisticRegression
LogisticRegr = LogisticRegression()
LogisticRegr.fit(X_train , Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [23]:
predictions = LogisticRegr.predict(X_test)

In [24]:
score =  LogisticRegr.score(X_test,Y_test)
print(score)

0.9644444444444444


In [25]:
from sklearn.metrics import confusion_matrix
matrix = confusion_matrix(Y_test,predictions)
print(matrix)

[[51  0  0  0  2  0  0  0  0  0]
 [ 0 40  0  0  0  1  0  0  1  0]
 [ 0  1 39  1  0  0  0  0  0  0]
 [ 0  0  0 49  0  0  0  0  3  0]
 [ 0  0  0  0 47  0  0  0  0  0]
 [ 0  0  0  0  0 37  0  0  0  2]
 [ 0  0  0  0  0  0 43  0  0  0]
 [ 0  0  0  0  0  0  0 47  0  1]
 [ 0  0  0  0  0  1  0  0 35  1]
 [ 0  0  0  0  0  1  0  0  1 46]]


In [26]:
from sklearn.metrics import classification_report

print(classification_report(Y_test, predictions))

             precision    recall  f1-score   support

          0       1.00      0.96      0.98        53
          1       0.98      0.95      0.96        42
          2       1.00      0.95      0.97        41
          3       0.98      0.94      0.96        52
          4       0.96      1.00      0.98        47
          5       0.93      0.95      0.94        39
          6       1.00      1.00      1.00        43
          7       1.00      0.98      0.99        48
          8       0.88      0.95      0.91        37
          9       0.92      0.96      0.94        48

avg / total       0.97      0.96      0.96       450

