In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"C:\Users\dell\Desktop\NEC\ShenyangPM20100101_20151231.csv")
df.head()

No  year  month  day  hour  season  PM_Taiyuanjie  PM_US Post  \
0   1  2010      1    1     0       4            NaN         NaN   
1   2  2010      1    1     1       4            NaN         NaN   
2   3  2010      1    1     2       4            NaN         NaN   
3   4  2010      1    1     3       4            NaN         NaN   
4   5  2010      1    1     4       4            NaN         NaN   

   PM_Xiaoheyan  DEWP   HUMI    PRES  TEMP cbwd     Iws  precipitation  Iprec  
0           NaN -26.0  69.79  1024.0 -22.0   NE  1.0289            NaN    NaN  
1           NaN -26.0  76.26  1024.0 -23.0   NE  2.5722            NaN    NaN  
2           NaN -27.0  69.56  1023.0 -23.0   NE  5.1444            NaN    NaN  
3           NaN -27.0  69.56  1023.0 -23.0   NE  7.7166            NaN    NaN  
4           NaN -27.0  69.56  1022.0 -23.0   NE  9.7744            NaN    NaN

In [3]:
df.isnull().sum()

No                   0
year                 0
month                0
day                  0
hour                 0
season               0
PM_Taiyuanjie    28196
PM_US Post       30904
PM_Xiaoheyan     27957
DEWP               692
HUMI               680
PRES               692
TEMP               692
cbwd               692
Iws                692
precipitation    12763
Iprec            12763
dtype: int64

In [4]:
df.describe()

No          year         month           day          hour  \
count  52584.000000  52584.000000  52584.000000  52584.000000  52584.000000   
mean   26292.500000   2012.499772      6.523962     15.726609     11.500000   
std    15179.837614      1.707485      3.448452      8.798896      6.922252   
min        1.000000   2010.000000      1.000000      1.000000      0.000000   
25%    13146.750000   2011.000000      4.000000      8.000000      5.750000   
50%    26292.500000   2012.000000      7.000000     16.000000     11.500000   
75%    39438.250000   2014.000000     10.000000     23.000000     17.250000   
max    52584.000000   2015.000000     12.000000     31.000000     23.000000   

             season  PM_Taiyuanjie   PM_US Post  PM_Xiaoheyan          DEWP  \
count  52584.000000   24388.000000  21680.00000  24627.000000  51892.000000   
mean       2.491100      81.189683     75.83750     75.240468      0.850304   
std        1.116988      80.112376     68.99593     78.404401     14.261483   
min        1.000000       1.000000      1.00000      2.000000    -97.000000   
25%        1.000000      32.000000     31.00000     28.000000    -11.000000   
50%        2.000000      59.000000     57.00000     51.000000      1.000000   
75%        3.000000     103.000000     97.00000     93.000000     14.000000   
max        4.000000    1528.000000    932.00000   1361.000000     28.000000   

               HUMI          PRES          TEMP           Iws  precipitation  \
count  51904.000000  51892.000000  51892.000000  51892.000000   39821.000000   
mean      63.006561   1016.005492      8.460495     19.816487       0.083895   
std       21.883355      9.724308     13.948303     32.135270       0.717721   
min        0.000000    988.000000    -28.000000      0.000000       0.000000   
25%       46.260000   1008.000000     -3.000000      3.000000       0.000000   
50%       64.720000   1016.000000     10.000000      8.000000       0.000000   
75%       82.010000   1024.000000     21.000000     23.000000       0.000000   
max      100.000000   1043.000000     35.000000    465.000000      33.100000   

              Iprec  
count  39821.000000  
mean       0.497750  
std        4.360741  
min        0.000000  
25%        0.000000  
50%        0.000000  
75%        0.000000  
max      120.000000

In [5]:
df.count()

No               52584
year             52584
month            52584
day              52584
hour             52584
season           52584
PM_Taiyuanjie    24388
PM_US Post       21680
PM_Xiaoheyan     24627
DEWP             51892
HUMI             51904
PRES             51892
TEMP             51892
cbwd             51892
Iws              51892
precipitation    39821
Iprec            39821
dtype: int64

In [6]:
df.columns

Index(['No', 'year', 'month', 'day', 'hour', 'season', 'PM_Taiyuanjie',
       'PM_US Post', 'PM_Xiaoheyan', 'DEWP', 'HUMI', 'PRES', 'TEMP', 'cbwd',
       'Iws', 'precipitation', 'Iprec'],
      dtype='object')

In [8]:
df1=df.drop(['No','year','month','day','hour','season','HUMI','PRES','precipitation','Iws','PM_Taiyuanjie','PM_Xiaoheyan','PM_US Post','cbwd','Iprec'],axis = 1)
df1.head()

DEWP  TEMP
0 -26.0 -22.0
1 -26.0 -23.0
2 -27.0 -23.0
3 -27.0 -23.0
4 -27.0 -23.0

In [9]:
df1.shape

(52584, 2)

In [10]:
df2=df1.dropna(axis = 0)
df2.head()

DEWP  TEMP
0 -26.0 -22.0
1 -26.0 -23.0
2 -27.0 -23.0
3 -27.0 -23.0
4 -27.0 -23.0

In [11]:
df2.isnull().sum()

DEWP    0
TEMP    0
dtype: int64

In [12]:
df3 = (df2-df2.min())/(df2.max()-df2.min())
df3.head()

DEWP      TEMP
0  0.568  0.095238
1  0.568  0.079365
2  0.560  0.079365
3  0.560  0.079365
4  0.560  0.079365

In [13]:
df_n= df3.select_dtypes(include = [np.number])
df_l = df_n.loc[:,['DEWP','TEMP']]
df_l.head()

DEWP      TEMP
0  0.568  0.095238
1  0.568  0.079365
2  0.560  0.079365
3  0.560  0.079365
4  0.560  0.079365

In [14]:
df_l.shape

(51892, 2)

In [15]:
x = np.array(df_l['DEWP']).reshape(51892,1)
y = np.array(df_l['TEMP']).reshape(51892,1)
x.shape
y.shape

(51892, 1)

In [16]:
from sklearn.model_selection import train_test_split
from sklearn import datasets, linear_model

In [17]:
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=0.20)
print(X_train.shape, Y_train.shape)
print(X_test.shape, Y_test.shape)

(41513, 1) (41513, 1)
(10379, 1) (10379, 1)


In [18]:
from sklearn.linear_model import LinearRegression

In [19]:
reg = LinearRegression()
reg.fit(X_train , Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [20]:
reg.coef_

array([[1.76417466]])

In [21]:
reg.intercept_

array([-0.80240272])

In [22]:
Y_prediction = reg.predict(X_test)
Y_prediction

array([[0.6371638 ],
       [0.19964849],
       [0.72184419],
       ...,
       [0.86297816],
       [0.87709156],
       [0.31255567]])

In [23]:
a = pd.DataFrame({"actual":list(Y_test),"prediction":list(Y_prediction)})
a.head()

actual             prediction
0   [0.7142857142857143]   [0.6371638022141053]
1  [0.12698412698412698]  [0.19964848687974635]
2   [0.6666666666666666]   [0.7218441858272071]
3   [0.7777777777777778]   [0.8206379667091592]
4   [0.6349206349206349]   [0.6089370076764049]