In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.svm import SVC
from sklearn.datasets import load_iris
from sklearn import metrics



In [6]:
iris = load_iris()
x = iris.data
y = iris.target

In [7]:
df = pd.DataFrame(iris.data)
df.head()

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

In [9]:
df1 = df.fillna(df.median())
df1.head()

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

In [10]:
dummies_frame = pd.get_dummies(df1)
df2= df1.reindex(columns = dummies_frame.columns, fill_value=1)
df2.head()

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, Y_train, Y_test = train_test_split(x,y,test_size=0.3,random_state=7)

In [13]:
X_train.shape, X_test.shape

((105, 4), (45, 4))

# kernel = Linear

In [44]:
model = SVC( kernel = 'linear')
#from sklearn import svm
#model =  svm.LinearSVC()

In [45]:
model.fit(X_train,Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [46]:
pred = model.predict(X_test)
pred

array([2, 1, 0, 1, 1, 0, 1, 1, 0, 1, 2, 1, 0, 2, 0, 2, 2, 2, 0, 0, 1, 2,
       1, 2, 2, 2, 1, 1, 2, 2, 2, 1, 0, 2, 1, 0, 0, 0, 0, 2, 2, 1, 2, 2,
       1])

In [47]:
metrics.accuracy_score(Y_test,pred)

0.9333333333333333

In [48]:
from sklearn.metrics import classification_report
print(metrics.classification_report(Y_test,pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        12
          1       0.93      0.88      0.90        16
          2       0.89      0.94      0.91        17

avg / total       0.93      0.93      0.93        45



In [69]:
from sklearn.metrics import confusion_matrix
matrix = confusion_matrix(Y_test,pred)
print(matrix)

[[12  0  0]
 [16  0  0]
 [17  0  0]]


# kernel = poly

In [71]:
model = SVC( kernel = 'poly')

In [72]:
model.fit(X_train,Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [73]:
pred = model.predict(X_test)
pred

array([2, 1, 0, 1, 1, 0, 2, 1, 0, 1, 2, 1, 0, 2, 0, 2, 2, 2, 0, 0, 1, 2,
       1, 1, 2, 2, 1, 1, 2, 2, 2, 1, 0, 2, 1, 0, 0, 0, 0, 2, 2, 1, 2, 2,
       1])

In [74]:
metrics.accuracy_score(Y_test,pred)

0.8888888888888888

In [75]:
from sklearn.metrics import classification_report
print(metrics.classification_report(Y_test,pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        12
          1       0.87      0.81      0.84        16
          2       0.83      0.88      0.86        17

avg / total       0.89      0.89      0.89        45



In [76]:
from sklearn.metrics import confusion_matrix
matrix = confusion_matrix(Y_test,pred)
print(matrix)

[[12  0  0]
 [ 0 13  3]
 [ 0  2 15]]


# kernel = Gaussian

In [77]:
model = SVC( kernel = 'rbf')

In [78]:
model.fit(X_train , Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [79]:
pred = model.predict(X_test)

In [80]:
metrics.accuracy_score(Y_test,pred)

0.9555555555555556

In [62]:
from sklearn.metrics import classification_report
print(metrics.classification_report(Y_test,pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        12
          1       1.00      0.88      0.93        16
          2       0.89      1.00      0.94        17

avg / total       0.96      0.96      0.96        45



In [81]:
from sklearn.metrics import confusion_matrix
matrix = confusion_matrix(Y_test,pred)
print(matrix)

[[12  0  0]
 [ 0 14  2]
 [ 0  0 17]]


# kernel = sigmoid

In [82]:
model = SVC( kernel = 'sigmoid')

In [83]:
model.fit(X_train,Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='sigmoid',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [84]:
pred = model.predict(X_test)

In [85]:
metrics.accuracy_score(Y_test,pred)

0.26666666666666666

In [86]:
from sklearn.metrics import classification_report
print(metrics.classification_report(Y_test,pred))

             precision    recall  f1-score   support

          0       0.27      1.00      0.42        12
          1       0.00      0.00      0.00        16
          2       0.00      0.00      0.00        17

avg / total       0.07      0.27      0.11        45



C:\Users\dell\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [87]:
from sklearn.metrics import confusion_matrix
matrix = confusion_matrix(Y_test,pred)
print(matrix)

[[12  0  0]
 [16  0  0]
 [17  0  0]]
